<!DOCTYPE html>
<html>
 
<head>
	<title>Lebensmittel Bestand</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="solarized_light.css">
	
	<h1>Vorratsübersicht</h1>
	</head>
	


<body>


<div id="menu font-size:2.4em">

	<a href="index.php">Produkt hinzufügen</a>
	<a href="overview.php">Bestand</a>
	<a href="suche.php">Suche</a>
	<a href="completeTable.php">löschen und ändern</a>

</div>
