<?php
	require_once 'config.php.inc';
	require_once 'functions.php.inc';

	//connect to DB
	try {
	   $sql = new PDO("mysql:host=localhost;dbname=$database", $username, $password);
	   $sql->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
	} catch (PDOException $e) {
	   print "Database Error: ".$e->getMessage();
	}

	//Useful for debugging!
	if($DEBUG == True) {
		//report all errors
		ini_set('error_reporting', E_ALL);
		ini_set('html_errors', 1);
		ini_set('display_errors', 1);
		//Throw an excaption if a query fails
		$sql->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	}


?>